### ISSUE TITLE
consoleUi.vi error

### ISSUE THREAD

**Issue by huipeng8** [Benji667/ErrorLog#2]
你好 Benji667,

感谢分享此项目，我下载了develop分支的代码，发现了一些小问题，我英语不是很好请允许我用中文发表相关评论，谢谢。

未安装相关依赖时consoleUi.vi报错，但是showConsoleUi.vi未正确捕获异常状态，导致Error Log Example无法显示consoleUi且未提示有效错误信息。

consoleUi.vi报错无法运行
![image](https://user-images.githubusercontent.com/17694228/154430520-a7e8bb28-58ae-408f-861e-f9183e3fcd8e.png)

showConsoleUi.vi此处未提示错误
![image](https://user-images.githubusercontent.com/17694228/154431077-6542674b-b52c-4ed7-9370-b8a3c29dd467.png)

主程序相关按钮没反应且未报错
![image](https://user-images.githubusercontent.com/17694228/154431381-178f5e09-789b-478a-98d5-5cda0a037198.png)

------------------------------
The following are from automatic translation:

Hello, benji667,

Thanks for sharing this project. I downloaded the code of the development branch and found some small problems. My English is not very good. Please allow me to comment in Chinese. Thank you.

Consoleui. When relevant dependencies are not installed VI reports an error, but showconsoleui VI the abnormal state is not captured correctly, so the error log example cannot display consoleui and does not prompt a valid error message.

consoleUi. VI error and unable to run
![image](https://user-images.githubusercontent.com/17694228/154430520-a7e8bb28-58ae-408f-861e-f9183e3fcd8e.png)

showConsoleUi. VI no errors are prompted here
![image](https://user-images.githubusercontent.com/17694228/154431077-6542674b-b52c-4ed7-9370-b8a3c29dd467.png)

The relevant buttons of the main program do not respond and no error is reported
![image](https://user-images.githubusercontent.com/17694228/154431381-178f5e09-789b-478a-98d5-5cda0a037198.png)

**Comment by Benji667** [comment]
Thanks so much for creating your feedback. 

The version you have doesn't handle properly uninstalled dependencies situation.  I have updated the source code to tackle it. 

Let me explain a bit. The goal with the **Serializer** class is to decouple our calling pieces of software from the serialization implementations. This abstract class provides logic agnostic methods to our Error Log. 

You can then independently implement any serializations, by creating **Serializer child** classes that have override VIs to concretely perform serialization operations. 

Finally, you have to implement a way to dynamically load concrete classes at runtime. This is done with the method, called Factory, in the Serializer class. 

Below the automatic translation in Simplified Chinese.

非常感谢您创建反馈。

您拥有的版本无法正确处理卸载依赖项的情况。 我已经更新了源代码来解决它。

让我解释一下。 **Serializer** 类的目标是将我们的调用软件与序列化实现分离。 这个抽象类为我们的错误日志提供了与逻辑无关的方法。

然后，您可以通过创建具有覆盖 VI 的 **Serializer 子** 类来独立实现任何序列化，以具体执行序列化操作。

最后，您必须实现一种在运行时动态加载具体类的方法。 这是通过 Serializer 类中称为 Factory 的方法完成的。

**Comment by Benji667** [comment]
@huipeng8 please sync to the _3aa71c9 - Homogenization of Front-Panels_ commit and let me know if you're still seeing the issue.

**Comment by huipeng8** [comment]
安装相关依赖后consoleUi.VI不再报错，但是范例依然没有正确运行。我觉得是consoleUi.VI事件结构的Timeout分支布尔状态错误，将“Run top level”分支设置成False后运行正常。谢谢。

After installing related dependencies, consoleui VI no longer reports errors, but the example still does not run correctly. I think it's consoleui The Boolean status of timeout branch of VI event structure is wrong. Set "run top level" branch to false and run OK. thank you.

![image](https://user-images.githubusercontent.com/17694228/154781670-72de5ba7-2507-4dda-b9b3-544e970a6633.png)

**Comment by Benji667** [comment]
Hi, 
This is due to the lack of a dependent package. You need to install them (I have added the [DEPENDENCIES.md](https://github.com/Benji667/ErrorLog/blob/62c48fd43f0aa8b40f2aa09ab6ceca6266c12837/DEPENDENCIES.md) for that). You can also use VI Package Manager to install the [Error Log.vipc](https://github.com/Benji667/ErrorLog/blob/62c48fd43f0aa8b40f2aa09ab6ceca6266c12837/src/Error%20Log.vipc).

**Comment by huipeng8** [comment]
抱歉我可能沒有說清楚，我安装了Error Log.vipc之前的问题已经解决了。

但是[consoleUi.vi](https://github.com/Benji667/ErrorLog/blob/develop/src/Handler.UserEvent.Console/consoleUi.vi)
![image](https://user-images.githubusercontent.com/17694228/154796913-1f28c464-8e65-4581-a9f5-6f58d9cf9649.png)此处可能需要检查一下，我觉得应该是False才对，可能你提交了一个比较旧的版本没有注意到这里。再次感谢你的分享。

**Comment by Benji667** [comment]
I'm sorry, my bad... Indeed, this case should be FALSE and the "idle" one to TRUE.

Thanks for you feedbacks!

**Comment by Benji667** [comment]
Isse fixed in f9e3d5d14215bc49b873bad9f8b6c5f4343ce813.
